import type { AnalysisResult, PublicAnalysisResult } from '@/types/analysis';

// Preview-safe: built only from fields already visible in the unpaid
// preview UI (risk level/score, summary, counts, the locked-finding
// titles already shown). Never touches evidence/explanation/action —
// those only exist client-side once /api/unlock has verified payment.
export function generatePreviewShareSummary(result: PublicAnalysisResult): string {
  const lines = [
    '🔎 Cap or Not Result',
    '',
    `Risk: ${result.riskLevel}`,
    `Score: ${result.riskScore}/100`,
    '',
    `${result.majorWarningsCount} major warning sign${result.majorWarningsCount !== 1 ? 's' : ''}, ${result.cautionSignalsCount} caution signal${result.cautionSignalsCount !== 1 ? 's' : ''} detected.`,
    '',
  ];

  const titles = [
    ...(result.previewFinding ? [result.previewFinding.title] : []),
    ...result.lockedFindingTitles.map((f) => f.title),
  ];
  if (titles.length > 0) {
    lines.push('What was flagged:');
    titles.forEach((title) => lines.push(`  • ${title}`));
    lines.push('');
  }

  lines.push(
    result.majorWarningsCount > 0
      ? 'Verify before paying or submitting personal information.'
      : 'No major red flags detected. Continue with normal verification.',
  );

  lines.push('', 'Generated by Cap or Not — verification indicators, not a definitive determination.');

  return lines.join('\n');
}

export function generateShareSummary(result: AnalysisResult): string {
  const lines = [
    '🔎 Cap or Not Result',
    '',
    `Risk: ${result.riskLevel}`,
    `Score: ${result.riskScore}/100`,
    '',
    `${result.majorWarnings.length} major warning sign${result.majorWarnings.length !== 1 ? 's' : ''} detected.`,
    '',
  ];

  if (result.majorWarnings.length > 0) {
    lines.push('Major warnings:');
    result.majorWarnings.slice(0, 4).forEach((f) => {
      lines.push(`  • ${f.title}`);
    });
    lines.push('');
  }

  if (result.majorWarnings.some((f) => f.category === 'payment')) {
    lines.push('⚠️ Payment request detected — verify before paying.');
  } else if (result.majorWarnings.length > 0) {
    lines.push('Verify before paying or submitting personal information.');
  } else {
    lines.push('No major red flags detected. Continue with normal verification.');
  }

  lines.push('', 'Generated by Cap or Not — verification indicators, not a definitive determination.');

  return lines.join('\n');
}

export function generateFullReport(result: AnalysisResult): string {
  const lines: string[] = [
    '━━━━━━━━━━━━━━━━━━━━',
    '',
    `Cap or Not Report`,
    '',
    `Risk Level: ${result.riskLevel}`,
    `Risk Score: ${result.riskScore}/100`,
    '',
    result.summary,
    '',
  ];

  if (result.majorWarnings.length > 0) {
    lines.push('🔴 MAJOR WARNING SIGNS', '');
    result.majorWarnings.forEach((f) => {
      lines.push(`  ${f.title}`);
      lines.push(`  Finding: ${f.finding}`);
      lines.push(`  Evidence: ${f.evidence}`);
      lines.push(`  Why it matters: ${f.explanation}`);
      lines.push(`  Action: ${f.action}`);
      lines.push('');
    });
  }

  if (result.cautionSignals.length > 0) {
    lines.push('🟠 CAUTION SIGNALS', '');
    result.cautionSignals.forEach((f) => {
      lines.push(`  ${f.title}`);
      lines.push(`  ${f.finding}`);
      lines.push('');
    });
  }

  if (result.positiveSignals.length > 0) {
    lines.push('🟢 POSITIVE SIGNALS', '');
    result.positiveSignals.forEach((f) => {
      lines.push(`  ${f.title}`);
      lines.push('');
    });
  }

  if (result.verificationGaps.length > 0) {
    lines.push('🔎 VERIFICATION GAPS', '');
    result.verificationGaps.forEach((g) => {
      lines.push(`  • ${g.item}`);
    });
    lines.push('');
  }

  lines.push('WHAT YOU SHOULD DO', '');
  result.recommendedAction.steps.forEach((step, i) => {
    lines.push(`  ${i + 1}. ${step}`);
  });
  lines.push('');
  lines.push(`BOTTOM LINE: ${result.recommendedAction.bottomLine}`);
  lines.push('', '━━━━━━━━━━━━━━━━━━━━', '');
  lines.push('Cap or Not provides risk indicators, not a definitive scam determination.');

  return lines.join('\n');
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}