import type { AnalysisResult } from '@/types/analysis';

export function generateShareSummary(result: AnalysisResult): string {
  const lines = [
    '🔎 Cap or Not Result',
    '',
    `Risk: ${result.riskLevel}`,
    `Score: ${result.riskScore}/100`,
    '',
    `${result.majorWarnings.length} major warning sign${result.majorWarnings.length !== 1 ? 's' : ''} detected.`,
    '',
  ];

  if (result.majorWarnings.length > 0) {
    lines.push('Major warnings:');
    result.majorWarnings.slice(0, 4).forEach((f) => {
      lines.push(`  • ${f.title}`);
    });
    lines.push('');
  }

  if (result.majorWarnings.some((f) => f.category === 'payment')) {
    lines.push('⚠️ Payment request detected — verify before paying.');
  } else if (result.majorWarnings.length > 0) {
    lines.push('Verify before paying or submitting personal information.');
  } else {
    lines.push('No major red flags detected. Continue with normal verification.');
  }

  lines.push('', 'Generated by Cap or Not — verification indicators, not a definitive determination.');

  return lines.join('\n');
}

export function generateFullReport(result: AnalysisResult): string {
  const lines: string[] = [
    '━━━━━━━━━━━━━━━━━━━━',
    '',
    `Cap or Not Report`,
    '',
    `Risk Level: ${result.riskLevel}`,
    `Risk Score: ${result.riskScore}/100`,
    '',
    result.summary,
    '',
  ];

  if (result.majorWarnings.length > 0) {
    lines.push('🔴 MAJOR WARNING SIGNS', '');
    result.majorWarnings.forEach((f) => {
      lines.push(`  ${f.title}`);
      lines.push(`  Finding: ${f.finding}`);
      lines.push(`  Evidence: ${f.evidence}`);
      lines.push(`  Why it matters: ${f.explanation}`);
      lines.push(`  Action: ${f.action}`);
      lines.push('');
    });
  }

  if (result.cautionSignals.length > 0) {
    lines.push('🟠 CAUTION SIGNALS', '');
    result.cautionSignals.forEach((f) => {
      lines.push(`  ${f.title}`);
      lines.push(`  ${f.finding}`);
      lines.push('');
    });
  }

  if (result.positiveSignals.length > 0) {
    lines.push('🟢 POSITIVE SIGNALS', '');
    result.positiveSignals.forEach((f) => {
      lines.push(`  ${f.title}`);
      lines.push('');
    });
  }

  if (result.verificationGaps.length > 0) {
    lines.push('🔎 VERIFICATION GAPS', '');
    result.verificationGaps.forEach((g) => {
      lines.push(`  • ${g.item}`);
    });
    lines.push('');
  }

  lines.push('RECOMMENDED ACTION', '');
  lines.push(result.recommendedAction);
  lines.push('', '━━━━━━━━━━━━━━━━━━━━', '');
  lines.push('Cap or Not provides risk indicators, not a definitive scam determination.');

  return lines.join('\n');
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
